agents:
  queue: "default"
  
steps:
  - label: "Display Environment Variables"
    command: "env"

  - label: "Build Frontend"
    command:
      - "cd pa_frontend && npm update"
      - "npm install --force"
      - "npm install register-service-worker --save"
      - "npm run build"
    agents:
      queue: "default"
    plugins:
      - docker#v3.8.0:
          image: "node:18"

  # - label: "Build Backend"
  #   command:
  #     - "export PATH=/usr/local/apache-maven-3.9.6/bin:$PATH"
  #     - "cd pa_backend && mvn clean install"
  #   agents:
  #     queue: "default"
  #   plugins:
  #     - docker#v3.8.0:
  #         image: "maven:3.9.6"
  #         environment:
  #           - "DATABASE_URL=postgresql://8.134.151.21:5432/swen90014_paplatypus_db"
  #           - "DATABASE_USER=swen90014_paplatypus_owner"
  #           - "DATABASE_PASSWORD=platypus"
  
- label: "Build and Deploy Backend"
  command: "mvn clean install"
  agents:
    queue: "default"
  plugins:
    - docker#v3.8.0:
        image: "maven:3.9.6" 
        volumes:
          - "./backend:/app" 
        workdir: "/app" 
        environment:
          - "DATABASE_URL=postgresql://8.134.151.21:5432/swen90014_paplatypus_db"
          - "DATABASE_USER=swen90014_paplatypus_owner"
          - "DATABASE_PASSWORD=platypus"