agents:
  queue: "default"
  
steps:
  - label: "Build Frontend"
    command:
      - "cd pa_frontend && npm update"
      - "cd pa_frontend && npm install --force"
      - "cd pa_frontend && npm install register-service-worker --save"
      - "cd pa_frontend && npm run build"
    agents:
      queue: "default"
    # plugins:
    #   - docker#v3.8.0:
    #       image: "node:18"

  - label: "Build Backend"
    command:
      - "cd pa_backend && mvn clean install"
    agents:
      queue: "default"
    # plugins:
    #   - docker#v3.8.0:
    #       image: "adoptopenjdk:20-jdk-hotspot"
    #       environment:
    #         - "DATABASE_URL=postgresql://8.134.151.21:5432/swen90014_paplatypus_db"
    #         - "DATABASE_USER=swen90014_paplatypus_owner"
    #         - "DATABASE_PASSWORD=platypus"
